#javac -encoding UTF-8 -d class Main.java | java -classpath ./class Main
#javac -encoding UTF-8 -d class ObjectClass.java | java -classpath ./class ObjectClass
#javac -encoding UTF-8 -d class BaseDataType.java | java -classpath ./class BaseDataType
#javac -encoding UTF-8 -d class StringClass.java | java -classpath ./class StringClass
#javac -encoding UTF-8 -d class ArrayClass.java | java -classpath ./class ArrayClass
#javac -encoding UTF-8 -d class DateClass.java | java -classpath ./class DateClass
#javac -encoding UTF-8 -d class BasicClass.java | java -classpath ./class BasicClass
#javac -encoding UTF-8 -d class OverrideClass.java | java -classpath ./class OverrideClass
#javac -encoding UTF-8 -d class PolymorphismClass.java | java -classpath ./class PolymorphismClass
